import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import {NextThemeProviders} from "../app/lib/NextUIThemeProvider";


import './globals.scss'
const inter = Lato({
  subsets: ['latin'],
  weight: '100'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextThemeProviders>
        {children}
        </NextThemeProviders>
        </body>
    </html>
  )
}
